### ISSUE TITLE
Proof of Expired Copyright?

### ISSUE THREAD

**Issue by ndo360** [roguephysicist/who_goes_there#1]
Greetings! I love this old Si-Fi thriller novella, but I was wondering how you came to the conclusion that the copyright was public domain? From the math I did, if it was renewed, then it would have be protected until mid 2030s. Please help explain the process you used to verify that it is in the public domain. (If it wasn't renewed then where is the proof that it wasn't?)

Cheers,
Noah.

**Comment by roguephysicist** [comment]
Hi Noah,

I have no proof that it is in the public domain. At the time I started this (early 2012), I couldn't find much information on the web concerning the copyright status; there were also some other John Campbell books in the public domain.

In all likelihood the story is still under copyright, although I do not know the specific details.

**Comment by ndo360** [comment]
Thanks for the response! I have been looking around as well without locating a clear answer. Hopefully an answer lends itself one way or another...

Keep up the good work!
Noah

**Comment by roguephysicist** [comment]
No problem. Do you have a project in mind that uses the text?

**Comment by ndo360** [comment]
I was wanting to make a podcast based off of it. Like a miniseries and such. Looking for some people to voice act in it.

**Comment by roguephysicist** [comment]
A quick search seems to yield the same result you mentioned -- namely, that it will be under copyright in the US until the mid 2030s.

I also just read that you are [required to have explicit permission](https://law.stackexchange.com/questions/6079/distributing-audiobooks-ive-narrated) in order to use a story, even if it is for non-commercial use.

Oddly enough, the only "official" version I was able to [find on Amazon](https://www.amazon.com/Who-Goes-There-Novella-Formed/dp/0982332203) is published by [Rocket Ride Books](https://www.facebook.com/pg/rocketridebooks/about/), who claim that the novella is their "flagship title" (they only have three published books). I suppose you could contact them and see what they have to say?

Keep me updated, if you don't mind. I'm interested in this as well.

Thanks,
Sean
